fixed typo
undef error - file error - parse error: AltPowerHomeView.ttml line
29-31: unexpected token ($)
  [% ELSE $]

<p><a href='https://altpower.usbm.ca/cgi-bin/index.cgi?site=[% SiteName
%] in AltPowerHomeView.ttml at Modules//Extropia/Core/Template.pm line
190.
 in HomeView.ttml at Modules//Extropia/Core/Template.pm line 190.
Compilation failed in require at index_debug.cgi line 59.